### ISSUE TITLE
Add title to the native chooser for Android

### ISSUE THREAD

**Issue by nerder** [HomeXLabs/open-mail-app-flutter#16]
It will be nice to have the possibility to add a title to the app chooser for Android devices

**Comment by MisterJimson** [comment]
Released in `0.0.6` and `0.1.0-nullsafety.1`

**Comment by nerder** [comment]
Thank you so much for the kudos and for taking the time and merging this! :)

One small feedback for next time is better to discuss changes in the PR since I struggle to find that the name of the variable was `nativePickerTitle` instead of `chooserTitle`

**Comment by MisterJimson** [comment]
Sure I could have put it on the release notes or commented on the PR. Thanks.
