### ISSUE TITLE
conflict in pipeline

### ISSUE THREAD

**Issue by PrinceGoyal** [HomeXLabs/open-mail-app-flutter#18]
kindly change android/gradle/wrapper/gradle-wrapper.properties - gradle-5.6.2-all.zip to gradle-5.6.4-all.zip

**Comment by MisterJimson** [comment]
Can you try with version `0.0.7` or `0.1.0-nullsafety.2`? Just updated to newest.

**Comment by leocuello** [comment]
Yes, it works, thank you
