### ISSUE TITLE
Error on Update Flutter 2.0.1

### ISSUE THREAD

**Issue by leocuello** [HomeXLabs/open-mail-app-flutter#22]
Error using dependency in Flutter v 2.0.1

ERROR:
Because open_mail_app >=0.0.3 <0.1.0-nullsafety.0 depends on url_launcher ^5.5.0 and wallet_app depends on url_launcher ^6.0.2, open_mail_app >=0.0.3 <0.1.0-nullsafety.0 is forbidden.
So, because wallet_app depends on open_mail_app ^0.0.8, version solving failed.
pub get failed (1; So, because wallet_app depends on open_mail_app ^0.0.8, version solving failed.)

**Comment by MisterJimson** [comment]
Done on version 0.1.0!
