### ISSUE TITLE
Platform.isAndroid and Platform.isIOS while flutter test 

### ISSUE THREAD

**Issue by PeterMee** [HomeXLabs/open-mail-app-flutter#29]
You are using Platform.isAndroid and Platform.isIOS in openMailApp (). It is a static property and cannot be simulated in the test. Can you use other platform checks so we can mimic the platform check in openMailApp () while a unit test like FakePlatform?

**Comment by MisterJimson** [comment]
Seems reasonable, do you have an example of a package that does this we can copy/learn from?

**Comment by PeterMee** [comment]
Hey, we switched for our projcet from `final isAndroid = Platform.isAndroid;` in `import 'dart:io';` to ` final isAndroid = const LocalPlatform().isAndroid;` in `import 'package:platform/platform.dart';`. That allows us to create a FakePlatform for the test. For more infos you can watch [LocalPlatform on flutter.dev](https://api.flutter.dev/flutter/package-platform_platform/LocalPlatform-class.html). It would be very nice and useful. Thanks.

**Comment by MisterJimson** [comment]
Can you take a look at https://github.com/HomeXLabs/open-mail-app-flutter/pull/30 and see if it fits your need? Added a sample test.

**Comment by PeterMee** [comment]
Perfekt! Exactly what we need. Thank you :)

**Comment by MisterJimson** [comment]
Closed in 0.3.0 :)
