### ISSUE TITLE
How to add mailto while opening mail app?

### ISSUE THREAD

**Issue by Alwin-Lazar** [HomeXLabs/open-mail-app-flutter#4]

**Comment by MisterJimson** [comment]
Are you trying to compose and email? With To, Subject, Body, etc?

If that is the case you should be using https://pub.dev/packages/url_launcher as mentioned in the readme.

This package is specially for just opening the mail app and getting a list of the installed main apps. No other function.

**Comment by Alwin-Lazar** [comment]
okey
