### ISSUE TITLE
Prefilling data

### ISSUE THREAD

**Issue by marguscrg** [HomeXLabs/open-mail-app-flutter#5]
It would be very useful if we could also prefill the email fields to, subject and body when opening the app.

It already works on Android with url_launcher, but such functionality on iOS would be useful.
This package seems quite close to this functionality if it only had prefilling.

This comment shows how it can be done on iOS for at least Gmail:
https://github.com/taljacobson/flutter_mailer/issues/29

**Comment by marguscrg** [comment]
map_launcher package does it for maps if it is of any help https://github.com/mattermoran/map_launcher/blob/master/ios/Classes/SwiftMapLauncherPlugin.swift

**Comment by MisterJimson** [comment]
@marguscrg thanks for the suggestion. `url_launcher` can already prefill email content on both Android and iOS and that is what should be used for that purpose.

This library is specifically for just opening a mail app or getting a list of installed mail apps so you can open them. Thats it.

From the readme: "If you want to compose an email or open any app with a mailto: link, you are looking for url_launcher"

**Comment by marguscrg** [comment]
Yes, I read the readme - I need to prefill data in the correct email app by showing the list of installed apps to the user first. url_launcher does not let me show the list of installed apps. Something like this does, but for Flutter: https://github.com/vtourraine/ThirdPartyMailer/blob/master/Sources/ThirdPartyMailer/ThirdPartyMailClient.swift

Thank you for the response though.

**Comment by MisterJimson** [comment]
Ah, I see. Yeah that’s unfortunately out of scope for the this project right now but I definitely see why url_launcher isn’t suitable either.
