### ISSUE TITLE
Add more features (Compose emails to specific apps)

### ISSUE THREAD

**Issue by CripyIce** [HomeXLabs/open-mail-app-flutter#6]
It's a great useful library, but why not adding support for recipients, subject, etc.?

**Comment by MisterJimson** [comment]
@CripyIce `url_launcher` already supports doing those actions. This library is more for opening specific email apps.

Can you comment on why `url_launcher` doesn’t fit your needs?

**Comment by CripyIce** [comment]
@MisterJimson Because of the same reason this library was made for.
In my app I want to open the "default" mail app on the device with `to`, `cc`, `subject` and `body`, and when using `url_launcher` I have to check if the user has the default iOS mail app and if not check if he has Gmail installed and so on..

**Comment by MisterJimson** [comment]
Great thanks I wanted to confirm thats the case. I'll leave this open and gather feedback. Originally this library was just designed to open the mail apps since that is what we needed but this use case makes sense.

**Comment by CripyIce** [comment]
Glad to hear that! Thanks!
Looking forward for this feature.

**Comment by MichaelSea206** [comment]
I agree with the other poster's suggestion. I just came across this package to make sure the user is able to send the correct e-mail app on their device, but then I want to populate that e-mail with our support e-mail address, a subject, and include some app info including the version in the body of the e-mail.

**Comment by davidmednikov** [comment]
Seems like a major need with iOS 14. url_launcher only opens up the Apple Mail app when it is set as the default for emails. It fails if any other email app is the default.

This plugin allows us to specify a different app which is great, but we need the ability to populate the emails similar to url_launcher.

Thanks in advance to the dev for a great plugin!

**Comment by NateWilliams2** [comment]
+1 to supporting this enhancement!

**Comment by MisterJimson** [comment]
As an update, I've spent a little bit of time on this but haven’t made huge progress. It seems different mail apps may handle the input params differently.

**Comment by bkoznov** [comment]
+1, this would be super useful. Even just a field or two, or just limited to a subset of email clients, would be great.

**Comment by binajmen** [comment]
+1 😉
